"""
CropGuard AI - Fertilizer & Nutrition Reference Data
------------------------------------------------------
Every entry is keyed by (crop, deficiency) - NOT deficiency alone.
This is what the admin panel's Fertilizer Rule Configurator manages,
and what /results looks up. Because dosages differ by crop (a rice paddy
and a tomato plant need very different Nitrogen dosing), keying only by
deficiency was the root cause of "same result for different crops."
"""

CROPS = ["Rice", "Tomato", "Maize", "Wheat", "Cotton", "Chilli", "Groundnut"]

# (crop, deficiency_type) -> treatment plan
FERTILIZER_RULES = {
    ("rice", "Nitrogen Deficiency"): dict(
        visual_symptoms="Yellowing starting at leaf tips of older/lower leaves, V-shaped chlorosis.",
        immediate_action="Apply split nitrogen top-dressing; avoid waterlogging that leaches N.",
        recommended_fertilizer="Urea (46-0-0)",
        application_method="Broadcast into standing water at tillering stage",
        dosage="40 kg/acre (100 kg/ha) split into 2 doses",
        recovery_time="10-14 days",
        risk_level="Moderate",
    ),
    ("rice", "Phosphorus Deficiency"): dict(
        visual_symptoms="Dark green/purplish leaves, stunted tillering, delayed maturity.",
        immediate_action="Basal apply phosphate before transplanting; correct soil pH if <5.5.",
        recommended_fertilizer="Single Super Phosphate (SSP, 16% P2O5)",
        application_method="Soil incorporation at land preparation",
        dosage="25 kg/acre (62 kg/ha)",
        recovery_time="14-21 days",
        risk_level="Moderate",
    ),
    ("rice", "Potassium Deficiency"): dict(
        visual_symptoms="Marginal scorching/browning of older leaves, weak stems, lodging.",
        immediate_action="Apply muriate of potash; improve field drainage.",
        recommended_fertilizer="Muriate of Potash (MOP, 60% K2O)",
        application_method="Split basal + top-dress at panicle initiation",
        dosage="20 kg/acre (50 kg/ha)",
        recovery_time="10-15 days",
        risk_level="Moderate",
    ),
    ("rice", "Iron Deficiency"): dict(
        visual_symptoms="Interveinal chlorosis on young leaves, leaves turn almost white in severe cases.",
        immediate_action="Foliar spray of chelated iron; correct alkaline soil pH.",
        recommended_fertilizer="Ferrous Sulphate (FeSO4) 0.5% foliar spray",
        application_method="Foliar spray, 2-3 applications 7 days apart",
        dosage="5 kg/acre in 200L water",
        recovery_time="7-10 days",
        risk_level="Low",
    ),
    ("rice", "Magnesium Deficiency"): dict(
        visual_symptoms="Interveinal yellowing on older leaves, orange-yellow leaf margins.",
        immediate_action="Apply magnesium sulphate; avoid excess potassium which blocks Mg uptake.",
        recommended_fertilizer="Magnesium Sulphate (Epsom salt)",
        application_method="Soil application or foliar spray",
        dosage="10 kg/acre",
        recovery_time="10-14 days",
        risk_level="Low",
    ),
    ("rice", "Zinc Deficiency"): dict(
        visual_symptoms="Stunted growth, bronzing of leaves, chlorotic striping near midrib.",
        immediate_action="Apply zinc sulphate to soil; drain field before application.",
        recommended_fertilizer="Zinc Sulphate (ZnSO4, 21%)",
        application_method="Soil broadcast before transplanting",
        dosage="10 kg/acre (25 kg/ha)",
        recovery_time="14-20 days",
        risk_level="Moderate",
    ),

    ("tomato", "Phosphorus Deficiency"): dict(
        visual_symptoms="Dark purplish underside of leaves, thin stems, poor root/fruit development.",
        immediate_action="Apply phosphate-rich fertilizer at root zone; maintain soil pH 6.0-6.8.",
        recommended_fertilizer="Diammonium Phosphate (DAP, 18-46-0)",
        application_method="Side-dress near root zone",
        dosage="15 kg/acre",
        recovery_time="12-18 days",
        risk_level="Moderate",
    ),
    ("tomato", "Nitrogen Deficiency"): dict(
        visual_symptoms="Uniform pale-green to yellow older leaves, spindly stems, reduced fruit set.",
        immediate_action="Apply balanced nitrogen; avoid over-application which delays fruiting.",
        recommended_fertilizer="Calcium Ammonium Nitrate (CAN)",
        application_method="Fertigation or side-dress",
        dosage="20 kg/acre split in 2 doses",
        recovery_time="7-12 days",
        risk_level="Moderate",
    ),
    ("tomato", "Potassium Deficiency"): dict(
        visual_symptoms="Marginal leaf scorch, blotchy fruit ripening, weak stems.",
        immediate_action="Apply potassium sulphate; ensure consistent irrigation.",
        recommended_fertilizer="Sulphate of Potash (SOP)",
        application_method="Fertigation or soil band application",
        dosage="18 kg/acre",
        recovery_time="10-15 days",
        risk_level="Moderate",
    ),
    ("tomato", "Iron Deficiency"): dict(
        visual_symptoms="Interveinal chlorosis on new growth, veins remain green.",
        immediate_action="Foliar iron chelate spray; check soil drainage/pH.",
        recommended_fertilizer="Iron EDTA chelate foliar spray",
        application_method="Foliar spray every 7 days",
        dosage="2-3 g/L water",
        recovery_time="7-10 days",
        risk_level="Low",
    ),
    ("tomato", "Magnesium Deficiency"): dict(
        visual_symptoms="Interveinal chlorosis on older leaves, leaf edges curl upward.",
        immediate_action="Foliar magnesium sulphate spray.",
        recommended_fertilizer="Magnesium Sulphate (Epsom salt) 2% foliar",
        application_method="Foliar spray",
        dosage="20g/L water, 2 sprays 10 days apart",
        recovery_time="10-14 days",
        risk_level="Low",
    ),
    ("tomato", "Zinc Deficiency"): dict(
        visual_symptoms="Small, narrow leaves (little leaf), interveinal chlorosis, rosetting.",
        immediate_action="Apply zinc sulphate; avoid excess phosphorus which locks zinc.",
        recommended_fertilizer="Zinc Sulphate foliar spray",
        application_method="Foliar spray",
        dosage="2g/L water",
        recovery_time="14-18 days",
        risk_level="Moderate",
    ),

    ("maize", "Nitrogen Deficiency"): dict(
        visual_symptoms="V-shaped yellowing from leaf tip along midrib on lower leaves.",
        immediate_action="Side-dress urea at knee-high stage; irrigate after application.",
        recommended_fertilizer="Urea (46-0-0)",
        application_method="Side-dress/band application",
        dosage="50 kg/acre split in 2-3 doses",
        recovery_time="10-14 days",
        risk_level="Moderate",
    ),
    ("maize", "Potassium Deficiency"): dict(
        visual_symptoms="Marginal firing/scorch on older leaves, weak stalks, lodging risk.",
        immediate_action="Apply MOP at knee-high stage; monitor stalk strength.",
        recommended_fertilizer="Muriate of Potash (MOP)",
        application_method="Band placement near roots",
        dosage="25 kg/acre",
        recovery_time="12-16 days",
        risk_level="Moderate",
    ),
    ("maize", "Magnesium Deficiency"): dict(
        visual_symptoms="Interveinal chlorosis with reddish-purple leaf margins on older leaves.",
        immediate_action="Foliar Epsom salt spray; correct soil acidity.",
        recommended_fertilizer="Magnesium Sulphate",
        application_method="Foliar spray",
        dosage="15g/L water",
        recovery_time="10-14 days",
        risk_level="Low",
    ),
    ("maize", "Zinc Deficiency"): dict(
        visual_symptoms="White/pale striping between veins, shortened internodes.",
        immediate_action="Apply zinc sulphate at planting or as foliar correction.",
        recommended_fertilizer="Zinc Sulphate",
        application_method="Soil band or foliar spray",
        dosage="10 kg/acre soil / 2g/L foliar",
        recovery_time="14-20 days",
        risk_level="Moderate",
    ),
    ("maize", "Iron Deficiency"): dict(
        visual_symptoms="Interveinal chlorosis on newest leaves, yellow-white striping.",
        immediate_action="Foliar iron chelate spray; improve drainage.",
        recommended_fertilizer="Ferrous Sulphate foliar spray",
        application_method="Foliar spray",
        dosage="5g/L water",
        recovery_time="7-10 days",
        risk_level="Low",
    ),
    ("maize", "Phosphorus Deficiency"): dict(
        visual_symptoms="Purplish leaf margins, stunted growth, delayed silking.",
        immediate_action="Apply starter phosphate fertilizer near root zone.",
        recommended_fertilizer="DAP (18-46-0)",
        application_method="Band placement at planting",
        dosage="20 kg/acre",
        recovery_time="14-18 days",
        risk_level="Moderate",
    ),

    ("wheat", "Nitrogen Deficiency"): dict(
        visual_symptoms="Pale green to yellow older leaves, reduced tillering.",
        immediate_action="Top-dress urea at crown root initiation and tillering stage.",
        recommended_fertilizer="Urea (46-0-0)",
        application_method="Top-dress broadcast",
        dosage="45 kg/acre split in 2 doses",
        recovery_time="10-14 days",
        risk_level="Moderate",
    ),
    ("wheat", "Potassium Deficiency"): dict(
        visual_symptoms="Marginal scorching on older leaves, weak straw, lodging.",
        immediate_action="Apply MOP at tillering stage.",
        recommended_fertilizer="Muriate of Potash",
        application_method="Broadcast/basal",
        dosage="20 kg/acre",
        recovery_time="12-15 days",
        risk_level="Moderate",
    ),
    ("wheat", "Iron Deficiency"): dict(
        visual_symptoms="Interveinal chlorosis on new leaves in calcareous soils.",
        immediate_action="Foliar iron chelate spray.",
        recommended_fertilizer="Ferrous Sulphate foliar spray",
        application_method="Foliar spray",
        dosage="5g/L water",
        recovery_time="7-10 days",
        risk_level="Low",
    ),
    ("wheat", "Magnesium Deficiency"): dict(
        visual_symptoms="Interveinal yellowing on older leaves with green veins.",
        immediate_action="Foliar magnesium sulphate application.",
        recommended_fertilizer="Magnesium Sulphate",
        application_method="Foliar spray",
        dosage="15g/L water",
        recovery_time="10-14 days",
        risk_level="Low",
    ),
    ("wheat", "Zinc Deficiency"): dict(
        visual_symptoms="Interveinal chlorotic bands, stunted plant height.",
        immediate_action="Apply zinc sulphate as soil or foliar treatment.",
        recommended_fertilizer="Zinc Sulphate",
        application_method="Soil/foliar",
        dosage="10 kg/acre soil / 2g/L foliar",
        recovery_time="14-18 days",
        risk_level="Moderate",
    ),
    ("wheat", "Phosphorus Deficiency"): dict(
        visual_symptoms="Dark bluish-green leaves, stunted growth, delayed heading.",
        immediate_action="Basal apply phosphate at sowing.",
        recommended_fertilizer="DAP (18-46-0)",
        application_method="Basal placement",
        dosage="25 kg/acre",
        recovery_time="14-20 days",
        risk_level="Moderate",
    ),

    ("cotton", "Potassium Deficiency"): dict(
        visual_symptoms="Marginal leaf yellowing/browning, premature boll shedding.",
        immediate_action="Apply SOP; critical during boll development stage.",
        recommended_fertilizer="Sulphate of Potash",
        application_method="Soil band + foliar top-up",
        dosage="25 kg/acre",
        recovery_time="12-16 days",
        risk_level="High",
    ),
    ("cotton", "Nitrogen Deficiency"): dict(
        visual_symptoms="Pale green foliage, reduced boll size, early leaf drop.",
        immediate_action="Split nitrogen application through vegetative and flowering stages.",
        recommended_fertilizer="Urea",
        application_method="Side-dress",
        dosage="35 kg/acre split in 3 doses",
        recovery_time="10-14 days",
        risk_level="Moderate",
    ),
    ("cotton", "Phosphorus Deficiency"): dict(
        visual_symptoms="Dark green leaves with reddish-purple tinge, delayed flowering.",
        immediate_action="Basal phosphate application at sowing.",
        recommended_fertilizer="SSP (16% P2O5)",
        application_method="Basal placement",
        dosage="20 kg/acre",
        recovery_time="14-18 days",
        risk_level="Moderate",
    ),
    ("cotton", "Magnesium Deficiency"): dict(
        visual_symptoms="Interveinal reddening on older leaves, brittle leaf texture.",
        immediate_action="Foliar Epsom salt spray.",
        recommended_fertilizer="Magnesium Sulphate",
        application_method="Foliar spray",
        dosage="15g/L water",
        recovery_time="10-14 days",
        risk_level="Low",
    ),
    ("cotton", "Iron Deficiency"): dict(
        visual_symptoms="Interveinal chlorosis on terminal leaves.",
        immediate_action="Foliar chelated iron spray.",
        recommended_fertilizer="Ferrous Sulphate foliar spray",
        application_method="Foliar spray",
        dosage="5g/L water",
        recovery_time="7-10 days",
        risk_level="Low",
    ),
    ("cotton", "Zinc Deficiency"): dict(
        visual_symptoms="Shortened internodes (little leaf), narrow chlorotic leaves.",
        immediate_action="Apply zinc sulphate at square formation stage.",
        recommended_fertilizer="Zinc Sulphate",
        application_method="Soil/foliar",
        dosage="10 kg/acre soil / 2g/L foliar",
        recovery_time="14-18 days",
        risk_level="Moderate",
    ),

    ("chilli", "Calcium/Blossom Stress"): dict(
        visual_symptoms="Blossom-end rot on fruit, marginal necrosis on young leaves.",
        immediate_action="Apply calcium nitrate foliar spray; maintain consistent soil moisture.",
        recommended_fertilizer="Calcium Nitrate foliar spray",
        application_method="Foliar spray",
        dosage="5g/L water, weekly",
        recovery_time="10-14 days",
        risk_level="Moderate",
    ),
    ("chilli", "Nitrogen Deficiency"): dict(
        visual_symptoms="Pale yellow-green older leaves, reduced fruit set.",
        immediate_action="Apply nitrogen in split doses through flowering.",
        recommended_fertilizer="Urea/CAN",
        application_method="Side-dress or fertigation",
        dosage="25 kg/acre split in 2-3 doses",
        recovery_time="10-14 days",
        risk_level="Moderate",
    ),
    ("chilli", "Potassium Deficiency"): dict(
        visual_symptoms="Marginal scorching, poor fruit color and pungency.",
        immediate_action="Apply SOP during fruit development.",
        recommended_fertilizer="Sulphate of Potash",
        application_method="Fertigation/soil band",
        dosage="18 kg/acre",
        recovery_time="10-15 days",
        risk_level="Moderate",
    ),
    ("chilli", "Iron Deficiency"): dict(
        visual_symptoms="Interveinal chlorosis on new leaves, veins stay green.",
        immediate_action="Foliar iron chelate spray.",
        recommended_fertilizer="Iron EDTA",
        application_method="Foliar spray",
        dosage="2-3g/L water",
        recovery_time="7-10 days",
        risk_level="Low",
    ),
    ("chilli", "Magnesium Deficiency"): dict(
        visual_symptoms="Interveinal yellowing on older leaves, leaf curling.",
        immediate_action="Foliar magnesium sulphate spray.",
        recommended_fertilizer="Magnesium Sulphate",
        application_method="Foliar spray",
        dosage="20g/L water",
        recovery_time="10-14 days",
        risk_level="Low",
    ),
    ("chilli", "Phosphorus Deficiency"): dict(
        visual_symptoms="Dark green/purplish leaves, poor root establishment.",
        immediate_action="Basal phosphate application.",
        recommended_fertilizer="DAP",
        application_method="Basal placement",
        dosage="15 kg/acre",
        recovery_time="14-18 days",
        risk_level="Moderate",
    ),

    ("groundnut", "Iron Deficiency"): dict(
        visual_symptoms="Interveinal chlorosis on young leaves, common in calcareous soils.",
        immediate_action="Foliar iron chelate spray, critical in high-pH soils.",
        recommended_fertilizer="Ferrous Sulphate foliar spray",
        application_method="Foliar spray, 2-3 applications",
        dosage="5g/L water",
        recovery_time="7-10 days",
        risk_level="Moderate",
    ),
    ("groundnut", "Nitrogen Deficiency"): dict(
        visual_symptoms="Pale green foliage; less critical due to N-fixing nodules but still occurs early.",
        immediate_action="Light starter nitrogen dose at sowing.",
        recommended_fertilizer="Urea (starter dose only)",
        application_method="Basal application",
        dosage="10 kg/acre (starter only)",
        recovery_time="10-14 days",
        risk_level="Low",
    ),
    ("groundnut", "Potassium Deficiency"): dict(
        visual_symptoms="Marginal chlorosis/scorch on older leaves, poor pod filling.",
        immediate_action="Apply potash at pegging stage.",
        recommended_fertilizer="Muriate of Potash",
        application_method="Soil band",
        dosage="20 kg/acre",
        recovery_time="12-16 days",
        risk_level="Moderate",
    ),
    ("groundnut", "Magnesium Deficiency"): dict(
        visual_symptoms="Interveinal yellowing on older leaves.",
        immediate_action="Foliar Epsom salt spray.",
        recommended_fertilizer="Magnesium Sulphate",
        application_method="Foliar spray",
        dosage="15g/L water",
        recovery_time="10-14 days",
        risk_level="Low",
    ),
    ("groundnut", "Zinc Deficiency"): dict(
        visual_symptoms="Chlorotic striping, stunted growth.",
        immediate_action="Apply zinc sulphate at sowing.",
        recommended_fertilizer="Zinc Sulphate",
        application_method="Soil application",
        dosage="10 kg/acre",
        recovery_time="14-18 days",
        risk_level="Moderate",
    ),
    ("groundnut", "Phosphorus Deficiency"): dict(
        visual_symptoms="Dark green leaves, poor root and pod development.",
        immediate_action="Basal phosphate critical for pod formation.",
        recommended_fertilizer="SSP",
        application_method="Basal placement",
        dosage="20 kg/acre",
        recovery_time="14-20 days",
        risk_level="Moderate",
    ),
}

# Generic fallback (used only if a truly novel crop/deficiency combo appears)
DEFAULT_TREATMENT = dict(
    visual_symptoms="Visible discoloration/stress pattern detected on leaf surface.",
    immediate_action="Consult local agronomist; consider soil test for precise diagnosis.",
    recommended_fertilizer="Balanced NPK (19-19-19)",
    application_method="Foliar spray as general corrective measure",
    dosage="As per local agri-extension guidance",
    recovery_time="10-15 days",
    risk_level="Moderate",
)


def get_treatment(crop_type, deficiency_type):
    key = (crop_type.lower().strip(), deficiency_type)
    return FERTILIZER_RULES.get(key, DEFAULT_TREATMENT)
